// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using cs1_countries_api.Data;

#nullable disable

namespace cs1_countries_api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230205100105_firstmigration")]
    partial class firstmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("cs1_countries_api.Model.AmericaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CapitalCity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("CityPopulation")
                        .HasColumnType("bigint");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Population")
                        .HasColumnType("bigint");

                    b.Property<int>("TotalArea")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AmericaCountries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CapitalCity = "new york city",
                            CityPopulation = 8467513L,
                            Currency = "Dollar",
                            Language = "English",
                            Name = "new york",
                            Population = 19680000L,
                            TotalArea = 141300
                        },
                        new
                        {
                            Id = 2,
                            CapitalCity = "Sacramento",
                            CityPopulation = 525041L,
                            Currency = "Dollar",
                            Language = "English",
                            Name = "california",
                            Population = 39240000L,
                            TotalArea = 423970
                        },
                        new
                        {
                            Id = 3,
                            CapitalCity = "Chicago",
                            CityPopulation = 2696555L,
                            Currency = "Dollar",
                            Language = "English",
                            Name = "illinois",
                            Population = 12580000L,
                            TotalArea = 149998
                        },
                        new
                        {
                            Id = 4,
                            CapitalCity = "Austin",
                            CityPopulation = 2176000L,
                            Currency = "Dollar",
                            Language = "English",
                            Name = "texas",
                            Population = 29530000L,
                            TotalArea = 695662
                        });
                });

            modelBuilder.Entity("cs1_countries_api.Model.AsiaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CapitalCity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("CityPopulation")
                        .HasColumnType("bigint");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Population")
                        .HasColumnType("bigint");

                    b.Property<int>("TotalArea")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AsiaCountries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CapitalCity = "Moskow",
                            CityPopulation = 12641000L,
                            Currency = "Rubel",
                            Language = "Russian",
                            Name = "russia",
                            Population = 143400000L,
                            TotalArea = 17100000
                        },
                        new
                        {
                            Id = 2,
                            CapitalCity = "Beijing",
                            CityPopulation = 21000000L,
                            Currency = "Juan",
                            Language = "Chinise",
                            Name = "china",
                            Population = 1412000000L,
                            TotalArea = 9597000
                        },
                        new
                        {
                            Id = 3,
                            CapitalCity = "Delhi",
                            CityPopulation = 32941000L,
                            Currency = "Rupee",
                            Language = "indian",
                            Name = "india",
                            Population = 1402000000L,
                            TotalArea = 3287000
                        },
                        new
                        {
                            Id = 4,
                            CapitalCity = "Soul",
                            CityPopulation = 9776000L,
                            Currency = "Won",
                            Language = "korean",
                            Name = "Korea",
                            Population = 51740000L,
                            TotalArea = 100210
                        });
                });

            modelBuilder.Entity("cs1_countries_api.Model.EuropeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CapitalCity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("CityPopulation")
                        .HasColumnType("bigint");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Population")
                        .HasColumnType("bigint");

                    b.Property<int>("TotalArea")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("EuropeCountries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CapitalCity = "Berlin",
                            CityPopulation = 3645000L,
                            Currency = "Euro",
                            Language = "German",
                            Name = "Germany",
                            Population = 83200000L,
                            TotalArea = 357588
                        },
                        new
                        {
                            Id = 2,
                            CapitalCity = "Warsaw",
                            CityPopulation = 1700139L,
                            Currency = "Zloty",
                            Language = "Polish",
                            Name = "Poland",
                            Population = 37750000L,
                            TotalArea = 312696
                        },
                        new
                        {
                            Id = 3,
                            CapitalCity = "Bern",
                            CityPopulation = 140000L,
                            Currency = "Swiss Frank",
                            Language = "German, French",
                            Name = "Switzerland",
                            Population = 8700000L,
                            TotalArea = 41285
                        },
                        new
                        {
                            Id = 4,
                            CapitalCity = "Amsterdam",
                            CityPopulation = 821752L,
                            Currency = "Euro",
                            Language = "Dutch",
                            Name = "Netherlands",
                            Population = 17530000L,
                            TotalArea = 41543
                        },
                        new
                        {
                            Id = 5,
                            CapitalCity = "Viena",
                            CityPopulation = 1800000L,
                            Currency = "Euro",
                            Language = "German",
                            Name = "Austria",
                            Population = 8900000L,
                            TotalArea = 83871
                        },
                        new
                        {
                            Id = 6,
                            CapitalCity = "Brussel",
                            CityPopulation = 1222637L,
                            Currency = "Euro",
                            Language = "German, Dutch, French",
                            Name = "Belgium",
                            Population = 11056000L,
                            TotalArea = 30688
                        },
                        new
                        {
                            Id = 7,
                            CapitalCity = "Prague",
                            CityPopulation = 1309000L,
                            Currency = "Czech Crown",
                            Language = "Czech",
                            Name = "Czech Republic",
                            Population = 10510000L,
                            TotalArea = 78870
                        },
                        new
                        {
                            Id = 8,
                            CapitalCity = "Bratislava",
                            CityPopulation = 475577L,
                            Currency = "Euro",
                            Language = "Slovak",
                            Name = "Slovakia",
                            Population = 5474000L,
                            TotalArea = 49035
                        },
                        new
                        {
                            Id = 9,
                            CapitalCity = "Paris",
                            CityPopulation = 2249975L,
                            Currency = "Euro",
                            Language = "French",
                            Name = "France",
                            Population = 67750000L,
                            TotalArea = 551695
                        },
                        new
                        {
                            Id = 10,
                            CapitalCity = "Rome",
                            CityPopulation = 2873000L,
                            Currency = "Euro",
                            Language = "Italian",
                            Name = "Italy",
                            Population = 59110000L,
                            TotalArea = 301230
                        },
                        new
                        {
                            Id = 11,
                            CapitalCity = "Madrid",
                            CityPopulation = 3223000L,
                            Currency = "Euro",
                            Language = "Spanish",
                            Name = "Spain",
                            Population = 47420000L,
                            TotalArea = 505990
                        },
                        new
                        {
                            Id = 12,
                            CapitalCity = "Budapest",
                            CityPopulation = 1756000L,
                            Currency = "Forint",
                            Language = "Hungarian",
                            Name = "Hungaria",
                            Population = 9967308L,
                            TotalArea = 93030
                        },
                        new
                        {
                            Id = 13,
                            CapitalCity = "Bucharest",
                            CityPopulation = 1830000L,
                            Currency = "Lei",
                            Language = "Romanian",
                            Name = "Romania",
                            Population = 19120000L,
                            TotalArea = 238400
                        },
                        new
                        {
                            Id = 14,
                            CapitalCity = "Kyjev",
                            CityPopulation = 3223000L,
                            Currency = "Hryvnia",
                            Language = "Ukrainian",
                            Name = "Ukraine",
                            Population = 43790000L,
                            TotalArea = 603700
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
